### ISSUE TITLE
question on bytes_per_row and threshold

### ISSUE THREAD

**Issue by jwijffels** [jcayzac/F9-Corner-Detection-Library#1]
hello, i'm trying this algorithm out
what are reasonable values of the parameters
bytes_per_row and threshold? can you clarify this?

**Comment by jcayzac** [comment]
Hi @jwijffels,
You're looking at some really old code 😄 

`bytes_per_row` is the size of an image row, in bytes. For an 8-bit grayscale image it's usually equal to the image width, or, if the format has some alignment constraints, might be the closest next value that is a multiple of 4, 8 or whatever the format says rows should align with.

`threshold` is the threshold below which differences in luminosity between adjacent pixels are ignored. Think of it as a smoothing parameter, kind of.

Hope it helps,
Julien.

**Comment by jwijffels** [comment]
thanks. 
regarding old code. do you believe the algorithm is outdated and other corner detection routines are better?

**Comment by jcayzac** [comment]
@jwijffels I guess everything can probably be computed more efficiently on the GPU, nowadays.

**Comment by jwijffels** [comment]
Thanks for the feedback. The speed of the algorithm is fine for my purposes.
I wrote a small R package around it, which is working nicely. 
I'll clean it up & document it before putting it available for R users.

**Comment by jwijffels** [comment]
FYI. I've put the R package at https://github.com/bnosac/image.CornerDetectionF9
